---
# INTERMEDIATE PYTHON PROGRAMMING
# CHAPTER 1 - Basic Python Syntax & Use of Markdown
---

# SHOWING TABLE OF CONTENTS
**Table of Contents** lets you show the ordered contents list (particularyly useful if you have a logn notebook) and lets you quickly navigate to various parts of notebook.  

In **Jupyter Lab**, to show the table of contentin, follow these steps
![Table of Content](./images/toc.png)



While in **Jupyter Notebook**, go to notebook main menu, and choose **View -> Table of Contents**

# RECAP on Jupyter Notebook Usage and Python Basic Syntax

## Hello World!

Type the following command to display `Hello, World!` greeting.

`print()` is a built-in Python function to produce screen outputs

```
print("Hello, World!")
```
To run a CELL
- Press `▶ Run` Button
- HOLD `SHIFT` + PRESS `ENTER`

It should print out the following texts right below the code cell:

```
Hello, World!
```

In [34]:
print("Hello, World!")

Hello, World!


In [24]:
# print something else here use print() function again


## To Run a Cell
Use mouse cursor to select a cell, and followed by either option below.
- Press ```▶ Run``` button
- ```SHIFT``` + ```ENTER``` to run and move on to the next cell
-  ```CMD``` + ```ENTER``` (Mac) or ```CTRL``` + ```ENTER``` (Win)  to run and stay at the current cell

To learn more keyboard shortcut, from menu choose **Help -> Show Keyboard Shortcuts**

In [373]:
import random
print(random.randrange(100,200))

161


## Navigate between Cells
Use keyboard ```UP``` and ```DOWN``` key to move between cells

## Variables
A variable can have a short name (like ```x``` and ```y```) or a more descriptive name (```age```, ```customer_name```, ```total_volume```).
```
x = 10
y = 20
customer_name = "Johnny"
```
- after declaring a variable, type variable in an empty cell will display its value
- or use ```print()```

In [131]:
x = 10

In [133]:
print(x)

10


In [135]:
x

10

If you refer to variable that doesn't exist yet or type the wrong name (case sensitive), it shows the following errro message 

`name ... is not defined`

In [143]:
print(y)

NameError: name 'y' is not defined

In [145]:
print(X)

NameError: name 'X' is not defined

## Variables Naming Rules
- A variable name must start with a **letter** or the **underscore character**
- A variable name CANNOT start with a number
- A variable name can only contain alpha-numeric characters and underscores (```A-Z```, ```a-z```, ```0-9```, and``` _``` )
- Variable names are case-sensitive (```age```, ```Age``` and ```AGE``` are three different variables)


In [150]:
address = "Cyberport"

In [152]:
address

'Cyberport'

### Legal Variable Names
```
myname = "John"
my_name = "John"
_my_name = "John"
myName = "John"
MYNAME = "John"
myName2 = "John"
```

### Illegal Variable Names
```
2myname = "John"
my-name = "John"
my name = "John"
```
Try typing the above to the cell below

### Making Comments in your code cell
In your code cell, start your lines with #

Example: <br>
```# This is a comment```

n = 100 ```# This is also a comment```

If you type above code to a cell, it will stay there, but those line(s) will be ignored when executing
- Comments can be used to explain Python codes/logics.
- Comments can be used to make the code more readable.
- Comments can be used to prevent execution when testing/debugging.

In [194]:
# declare a customer's name
customer_name = "Casey"

In [196]:
customer_name

'Casey'

In [200]:
customer_name.upper() # this line will display customer name in upper-case

'CASEY'

## Celll Mode
- **Edit Mode**: click **inside** a cell to enter edit mode.
- **Command Mode**: click **outside** a cell to enter Command Mode.
- While in Edit Mode, press ```ESC``` key to enter Command Mode
- While in Command Mode, press `ENTER` key to enter Edit Mode

## A Few Keyboard Shortcuts
Programming is a keyboard-intensive activity, picking up a few keyboard shortcuts will reducing your hand-switching between keyboard and mouse/trackpad and therefore will greatly increase your coding productivity.

Make sure you are in **Command Mode** when you plan to use keyboard shortcuts.  When you are in editing mode, all the keyboard pressing becomes editing of the cell contents.

### Shortcut for Inserting a Cell
In **Command Mode**, Press `A` to insert above, Press `B` to insert below

In [451]:
# Move this cell active cell by clicking the OUTSIDE area of cell
# Make sure you are in Command mode
# press A to insert a cell above this cell
# press B to insert a cell below this cell

### Shortcut for Deleting a Cell
In **Command Mode**, Press ```D```, ```D``` (Press D TWICE)

In [ ]:
# cell to delete - 1

In [ ]:
# cell to delete - 2

In [ ]:
# cell to delete - 3

### Shortcut to **UNDO** action/actions
In **Command Mode**, Press ```Z```

## Cell Types
There are TWO cell types.
- **Code**: let you type python code(s) and python comments
- **Markdown**: let you create descriptive texts (a.k.a notes) for your data analysis project.  That's why we are calling it notebooks.

When you create a new cell, by default it is a **code** shell.

You can change a cell from **code** to **markdown** by pressing `m` key (make sure you are in **Command** mode)

You can change a cell from **markdown** to **code** by pressing `y` key (make sure you are in **Command** mode)

Note: if you see a pair of square brackets `[ ]` in front a cell, that indicates it's a **code** cell. 

## Editting Markdown Cell
You can double-click a markdown cell to enter markdown editting mode.  
Once you are done editting the markdown cell, press `RUN` to render the markdown cell to display rich descriptive notes.


## Use `TAB` Key and `ENTER` key for Code Completion

## Variable Name Completion
We've previously defined `customer_name` variable, to refer to this long variable name, you can just type the first few characters of the variable and press `TAB` to prompt for options of code completion.

e.g.<br>
`cu`+`TAB` <br>
wait for the code completion options and press `ENTER` to complete the code

In [204]:
customer_name

## Function Name Completion

If you like to call a built-in function without typing the full function name, type below to get prompts of code completion.

`customer_name.u`+`TAB`

Remember to append `()` to the end of the function name to invoke the function.  Without the pair of parenthese, the will instead shows the function desription.

In [221]:
customer_name.upper()

'CASEY'

## String Interpolation
Add a preceeding `f` to the string and use `{}` to refer to a variable.
```
first_name = "James"
last_name = "Bond"
print(f"My name is {last_name}. {first_name} {last_name}.")
```

In [245]:
first_name = "James"
last_name = "Bond"
print(f"My name is {last_name}. {first_name} {last_name}.")

My name is Bond. James Bond.


## Python Data Types
- Text Type:	```str```
- Numeric Types:	```int```, ```float```, ```complex```
- Sequence Types:	```list```, ```tuple```, ```range```
- Mapping Type:	```dict```
- Set Types:	```set```, ```frozenset```
- Boolean Type:	```bool```
- Binary Types:	```bytes```, ```bytearray```, ```memoryview```

In [249]:
x = 100
y = 20.5
my_name = "James Bond"

## Type Checking
You can use `type()` function to check verify the type of a variable.

In [252]:
type(x)

int

In [254]:
type(y)

float

In [256]:
type(my_name)

str

## Type Confusion Errors
Typing is a challenging concept to beginner.  Many programming errors rooted to programmer's confusion in types.

In [265]:
# the line below works
print(x + y) # it is okay to add a float number to an int

120.5


In [263]:
# the line below doesn't work
print(x + my_name) # it is NOT okay to add a string to an integer number


TypeError: unsupported operand type(s) for +: 'int' and 'str'

## More on Type Confusion

declare `i` is a number
```
i = 10
```

In [329]:
i = 10

In [293]:
# the result is 20
i + i

20

declare `j` is a string
```
j = "10"
```

In [331]:
j = "10"

In [302]:
# the result is '1010'
# j is a string, when + is applied, it concatenates two string
j + j

'1010'

Type the following code

`i/3` 

It gives 3.333333333333...

In [320]:
i/3

3.3333333333333335

Type the following code

`j/3` 

It produces an error

In [324]:
j/3

TypeError: unsupported operand type(s) for /: 'str' and 'int'

### Always use `type()` function to verify the type of variables
```
type(i)
type(j)
```

In [306]:
type(i)

int

In [347]:
type(j)

str

## Type Conversion

Use the following type casting function to force a conversion of data type

```
int()
float()
str()
bool()
bytes()
```

In [343]:
# j + j produces 1010
j + j

'1010'

In [341]:
# int(j) + int(j) produces 20
int(j) + int(j)

20

## Operators
Operators are used to perform operations on variables and values.
- Arithmetic operators: ```+, -, *, /, %, **, //```
- Assignment operators: ```=, +=```
- Comparison operators: ```==, !=, >=```
- Logical operators: ```and, or, not```
- Identity operators: ```is, is not```
- Membership operators: ```in, not in```
- Bitwise operators: ```&,|, ^, ~, <<, >>```

## Arithmetic Operators

- ```+```	Addition	```x + y```
- ```-```	Subtraction	```x - y```
- ```*```	Multiplication	```x * y```
- ```/```	Division	```x / y```
- ```%```	Modulus	```x % y```
- ```**```	Exponentiation	```x ** y```
- ```//```	Floor division	```x // y```

## Comparison Operators
- Equal	```x == y```
- Not equal	```x != y```
- Greater than	```x > y```
- Less than	```x < y```
- Greater than or equal to	```x >= y```
- Less than or equal to	```x <= y```


## Logical Operators

- ```and``` 	Returns True if both statements are true	```x < 5 and  x < 10```	
- ```or```	Returns True if one of the statements is true	```x < 5 or x < 4```	
- ```not```	Reverse the result, returns False if the result is true	```not(x < 5 and x < 10)```

## Looping

```
students = ["April", "Ben", "Cathy", "Danny", "Eve"]
for student in students:
    print(student)
```

In [397]:
students = ["April", "Ben", "Cathy", "Danny", "Eve"]
for student in students:
    print(student)

April
Ben
Cathy
Danny
Eve


## Dictionary
- A dictionary is a collection of related data. 
- In Python dictionaries are written with curly brackets **{ }**, and they have ***keys*** and ***values***.

**Create and print a dictionary**:
```
client = {
    "id": 888,
    "company": "ABC Co.",
    "email": "hello@abc.com"
}

client
client["email"]
client.get("email")
client["email"] = "hi@abc.com"
```

In [403]:
client = {
    "id": 888,
    "company": "ABC Co.",
    "email": "hello@abc.com"
}

In [405]:
client

{'id': 888, 'company': 'ABC Co.', 'email': 'hello@abc.com'}

In [407]:
client["email"]

'hello@abc.com'

In [412]:
client.get("email")

'hello@abc.com'

In [415]:
client["email"] = "hi@abc.com"

In [417]:
client

{'id': 888, 'company': 'ABC Co.', 'email': 'hi@abc.com'}

In [419]:
print(client)

{'id': 888, 'company': 'ABC Co.', 'email': 'hi@abc.com'}


# BASIC NUMPY SYNTAX
- NumPy is a python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy stands for Numerical Python.

## Installation of numpy
numpy is already included in anaconda, so NO need to install

If you use regular python, you can install with pip
```
pip install numpy
```

## import before you use it
- Once NumPy is installed, **import** it in your applications by adding the `import` keyword:
- You will see an error message if didn't import it first
- NumPy is usually imported under the np alias.

```
import numpy as np
print(np.__version__)

```

'1.26.4'

## Why `numpy`
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up a lot faster.
- The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.
- Pandas will built-on top of numpy and often used together with numpy

Let's compare the experience of using a regular python list to numpy array

`a_list = [1,2,3,4,5]` - Create a regular python list

`np_list = np.array([1,2,3,4,5])` - create a numpy array

`type(a_list)`  - it says 'list'

`type(np_list)` - it says 'numpy.ndarray'

`a_list + 100` - TypeError: a regular number CANNOT adds to a list

`np_list + 100` - It smartly repetitively add 100 to each number in the array. A for lopp is quietly running behind the scene without bothering us to write one.



In [470]:
a_list = [1,2,3,4,5]

In [483]:
np_list = np.array([1,2,3,4,5])

In [485]:
type(a_list)

list

In [487]:
type(np_list)

numpy.ndarray

In [478]:
a_list + 100

TypeError: can only concatenate list (not "int") to list

In [480]:
np_list + 100

array([101, 102, 103, 104, 105])

Try other arithmetic operators like below.  Again a for loop is quietly running behind the scene to repetitively performe the same operation to each element of the numpy array.  This fits out need in the use case of data science.

```
np_list * 100
np_list / 100
np_list > 3
```

In [497]:
np_list * 100

array([100, 200, 300, 400, 500])

In [499]:
np_list > 3

array([False, False, False,  True,  True])

In [502]:
np_list.dtype

dtype('int64')

## `arange()` method
- `arange()` is one of the array creation routines based on numerical ranges. 
- It creates an instance of ndarray with evenly spaced values and returns the reference to it.

**Syntax**:
```
numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray
```

**Example**:
```
np.arange(0, 20, 2)
```


## Iterating Arrays
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.
```
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)
```

**Note**: In a 2-D array it will go through all the rows for each loop

## Filter
- Getting some elements out of an existing array and creating a new array out of them is called filtering.
- You filter an array using a index flag list: `[True, False, True, False]`
- A boolean index list is a list of booleans corresponding to indexes in the array.
- If the value at a matching position is `True`, that element is contained in the result, if the value at that index is `False`, that element is excluded from the result.

**Example**:
```
import numpy as np
arr = np.arange(101, 111) # create a list from 101 to 110
x = [True, False, False, False, False, False, False, False, False, True]
new_arr = arr[x]
print(new_arr)
```

In [525]:
import numpy as np
arr = np.arange(101, 111) # create a list from 101 to 110
x = [True, False, False, False, False, False, False, False, False, True]
new_arr = arr[x]
print(new_arr)

[101 110]


## More on Filtering

```
arr = np.arange(101, 111) # create a list from 101 to 110
filter_flags = arr > 105
new_arr = arr[filter_flags]
print(filter_flags)
print(newarr)
```

In [533]:
arr = np.arange(101, 111) # create a list from 101 to 110
filter_flags = arr > 105
new_arr = arr[filter_flags]
print(filter_flags)
print(new_arr)

[False False False False False  True  True  True  True  True]
[106 107 108 109 110]


## Challenge
retrieve all the even number from the array in the previous step

**hint**: use `%` (modulus operator)  


## Generating Random Array

use the following code to import numpy's random class
```
from numpy import random
```

The `randint()` method takes a size parameter where you can specify the shape of an array.

**Example**:
```
x=random.randint(100, size=(3))
y=random.randint(100, size=(3,4))
z=random.rand(4,5)
print(x)
print(y)
print(z)
```

In [549]:
# import here
from numpy import random

In [574]:
random.randint(100, size=(3))

array([55,  1, 16])

**To keep running a same cell**:

Hold `CMD` (Mac) / `CTRL` (Windows) + `ENTER`

## Generating random number from array
- The choice() method allows you to generate a random value based on an array of values.
- The choice() method takes an array as a parameter and randomly returns one of the values.

```
x = random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"])
y = random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"], size=(3,2))
z = random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"], size=(3,2))

print(x)
print(y)
print(z)
```

In [651]:
x = random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"])
y = random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"], size=(3,2))
z = random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"], size=(3,2))

print(x)
print(y)
print(z)

3
[['Q' 'K']
 ['Q' 'A']
 ['9' '5']]
[['Q' 'Q']
 ['8' 'Q']
 ['9' 'J']]


# KEYBOARD SHORTCUTS

Picking up a few keyboard shortcuts will speed up your code speed in great deal.  

Most keyboard shortcuts are for **COMMAND MODE**. A small number are for **EDIT MODE**

## Shortcuts in _command mode_

| Key                    | Function                                    |
| ---------------------- | ------------------------------------------- |
| `Enter`                | enter _edit mode_ in the active cell        |
|`Cmd+Enter` (Mac) or `Ctrl+Enter` (Windows) | run and stay at the current cell |
| `Up`                   | to navigate to upper cell                   |
| `Down`                 | to navigate to lower cell                   |
| `A`                    | insert a new cell above the active cell     |
| `B`                    | insert a new cell below the active cell     |
| `M`                    | make the active cell a Markdown cell        |
| `Y`                    | make the active cell a code cell            |
| `Shift` + `Up Arrow`   | select the current cell and the cell above  |
| `Shift` + `Down Arrow` | select the current cell and the cell below  |
| `Ctrl` + `A`           | select all cells                            |
| `X`                    | cut the selected cell or cells              |
| `C`                    | copy the selected cell or cells             |
| `V`                    | paste the cell(s)                           |
| `Shift + M`            | merge multiple selected cells into one cell |
| `DD` (`D` twice)       | delete the active cell                      |
| `Z`                    | undo most recent command mode action        |

## Shortcuts in _edit mode_

| Key                         | Function                            |
| --------------------------- | ----------------------------------- |
| `Esc`                       | to enter _command mode_             |
| `Tab`                       | for code completion                 |
| `Shift` + `Tab`             | for tooltip help                    |
| `Ctrl` + `Shift` + `-`      | split the active cell at the cursor |
| `Ctrl` + `/` or `Cmd` + `/` | toggle comment      

## Multiple Lines/Cursors

Press and hold `OPTION` (on Mac) or `ALT` (on Windows) to select mulple lines

Press and hold `OPTION + CMD` (on Mac) or `ALT + CTRL` (on Windows) to add multiple cursors

Press and hold `OPTION + SHFIT` (on Mac) or `ALT + SHIFT` (on Windows) to duplicate line(s)


Try that with the following codes
```
greeting1 = 'I am April'
greeting2 = 'I am Ben'
greeting3 = 'I am Cathy'
```

```
print(greeting1)
print(greeting2)
print(greeting3)
```

In [663]:
greeting1 = 'I am April.'
greeting2 = 'I am Ben.'
greeting3 = 'I am Cathy.'

In [669]:
print(greeting1)
print(greeting2)
print(greeting3)

I am April.
I am Ben.
I am Cathy.


# Help

Prepend a `?` to a library name, method name or variable name, you can access the Docstring for quick reference

**Example**

```
?print
?str.upper
?pd.read_csv
?pd.read_excel
```

**Or use `SHIFT`+`TAB` to prompt quick reference**

`print`+`SHIFT`+`TAB`

`str.upper`+`SHIFT`+`TAB`


# MASTERING MARKDOWND SYNTAX

## What is Markdown?

Markdown is a lightweight markup language that you can use to add rich formatting to plaintext text documents.

Markdown is widely used in Jupyter Notebook for adding rich descriptive contents and instructions.

## Basic Syntax

![Markdown Cheat Sheet](https://res.cloudinary.com/practicaldev/image/fetch/s--2rTn_7XO--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/5zhubbpov3m3ly9a1t9c.png)

### Various Heading 

Start with `#` to create heading of various sizes.  
One `#` for heading size 1  
Two `#` for heading size 2  
and so on ...

```
# Heading 1 (biggest heading)
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5
###### Heading (smallest heading)
```

### Bold Text
Wrap text between a pair of `**` to make it bold.

Example code:
```
This is **Bold** text.
```

### Italic Text
Wrap text between a pair of `_` to make it italic.

Example code:
```
This is _Italic_ text.
```

### Unordered List
Add a preceeding `-` to each list item

```
- item
- item again
- item again and again
```

### Ordered List
Add a preceeding number `1`+`.` to each list item

```
1. item
2. item again
3. item again and again
```

item
item again
item again and again

### Hyperlink

Use a pair of square brackets and a pair of parentheses  
**Syntax**: `[Display Text](Destination Link)`

**Example**:
```
Apple Web Site: [Apple](https://www.apple.com)
```

### Add image to your 

Start with exclamation mark and followed by a pair of square brackets and a pair of parentheses.  

**Syntax**:`![]()`

**Example**:
```
![HKU Business School Logo](https://www.hkubs.hku.hk/ciec/wp-content/uploads/HKU_Business_School_Logo_Color.png)
```

### Highlighting Program Codes

**Inline Program Codse**: 
```
a code statement here: `i = 100`
```


## Markdown Playground 

The following page let you type markdown and provide instant live rendering/preview

[dillinger.io](https://dillinger.io/)

## More on Markdown

[More Markdown Syntax](https://www.markdownguide.org/basic-syntax/)

# EXERCISE #1 - Create Your Personal Profile Using Markdown

Use markdown to build you online profile.
- Go to **Moodle** to download the exercise description.
- Follow the instructor's steps to build you online profile.  This only profile can be use for your Github account.
- Submit your completed markdown personal profile to Moodle.
- This exercise weighs 10 marks.